const ALERT_SHOW_TIME = 5000;

const RERENDER_DELAY = 500;

const HIDDEN_STATE = 'hidden';
const MODAL_OPEN_STATE = 'modal-open';

const COUNT_RANDOM_PICTURES = 10;

const COUNT_COMMENTS_TO_LOADER = 5;

const FILE_TYPES = ['gif', 'jpg', 'jpeg', 'png'];

export {ALERT_SHOW_TIME, RERENDER_DELAY, HIDDEN_STATE, MODAL_OPEN_STATE, COUNT_RANDOM_PICTURES, COUNT_COMMENTS_TO_LOADER, FILE_TYPES};
